### PR TITLE
V1.11

### PR DESCRIPTION
**Pull request by Graeme-Smith**
1. Added to additional sections to README:
- Instructions to running script from command line
- Details on running Pytest suite

2. Simplified code processing the input parameters

3. Added tests:
- _test_inputs.py_ - this tests that various combinations of input parameters don't brak the app.
- _test_outputs.py_ - this tests data run through a previous version of the app for MokaWES, MokaPipe, and MokaAmp and checks that the output is similar.

---
This change is [Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_sambamba_chanjo/36)

### CODE REVIEW

**Review by aledj2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_sambamba_chanjo/36)* status: 0 of 4 files reviewed, 17 unresolved discussions (waiting on @aledj2 and @Graeme-Smith)

___
*[README.md, line 1 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_sambamba_chanjo/36#-MppnBJx0FGVTw8X4Bfa:-MppnBJx0FGVTw8X4Bfb:b-pq2fuh) ([raw file](https://github.com/moka-guys/dnanexus_sambamba_chanjo/blob/b633a749fbb3c5553bc36cf0fe463382227eca73/README.md#L1)):*
> ```Markdown
> # dnanexus_sambamba_chanjo - v1.11
> ```

is this the right version/release?v1.13 now?
___
*[README.md, line 43 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_sambamba_chanjo/36#-MppnZck-rSh0qu_hvV8:-MppnZck-rSh0qu_hvV9:bmx5q8v) ([raw file](https://github.com/moka-guys/dnanexus_sambamba_chanjo/blob/b633a749fbb3c5553bc36cf0fe463382227eca73/README.md#L43)):*
> ```Markdown
> 8. Exclude duplicate reads? This True/False boolean denotes whether to filter out reads that have failed quality control `- F not failed_quality_control`. True excludes reads that have failed quality control, false includes them.
> 9. There is an `additional_sambamba_flags` free form text box for passing additional flags to Sambamba, this excludes arguments passed as a text string to the -F filter flag which are passed using `additional_filter_commands`.
> 10. There is an `additional_filter_commands` free form text box for passing additional arguments as a text string to the Sambamba -F filter flag.  Commands are appended to the existing filter created by using the .
> ```

some missing text here? from current master branch:

so the text must start ` and ...`, where ... is the additional filter command (also note the leading space before `and`).
___
*[README.md, line 63 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_sambamba_chanjo/36#-MppnkB_AQBetxkFhYUK:-MppnkB_AQBetxkFhYUL:b-oqgnv2) ([raw file](https://github.com/moka-guys/dnanexus_sambamba_chanjo/blob/b633a749fbb3c5553bc36cf0fe463382227eca73/README.md#L63)):*
> ```
> 11
> ```
v1.13
___
*[README.md, line 64 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_sambamba_chanjo/36#-Mppnmzb4z0MxhnVpjyb:-Mppnmzb4z0MxhnVpjyc:bqfy492) ([raw file](https://github.com/moka-guys/dnanexus_sambamba_chanjo/blob/b633a749fbb3c5553bc36cf0fe463382227eca73/README.md#L64)):*
> ```Markdown
> ```bash
> dx run 001_ToolsReferenceData:/Apps/chanjo_sambamba_coverage_v1.11 \
> --name "congenicaV1.11_test_standard settings" \
> ```

example name
___
*[README.md, line 65 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_sambamba_chanjo/36#-MppnprP2c247ME3Po4G:-MppnprP2c247ME3Po4H:bw250lf) ([raw file](https://github.com/moka-guys/dnanexus_sambamba_chanjo/blob/b633a749fbb3c5553bc36cf0fe463382227eca73/README.md#L65)):*
> ```
> ject-PXH0qBZHXlfT2JYf7aMcHMxQk:file-cg
> ```
prob don't want to provide real example files?
___
*[README.md, line 72 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_sambamba_chanjo/36#-Mppo0rVAhnNCZAcJxSf:-Mppo0rVAhnNCZAcJxSg:b-e5qu) ([raw file](https://github.com/moka-guys/dnanexus_sambamba_chanjo/blob/b633a749fbb3c5553bc36cf0fe463382227eca73/README.md#L72)):*
> ```Markdown
> -i exclude_duplicate_reads=true \
> -i coverage_level="150" \
> -i additional_sambamba_flags="" \
> ```

can we give examples here?
___
*[README.md, line 73 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_sambamba_chanjo/36#-MppnxPq6q5qg2xHdX7T:-MppnxPq6q5qg2xHdX7U:b-e5qu) ([raw file](https://github.com/moka-guys/dnanexus_sambamba_chanjo/blob/b633a749fbb3c5553bc36cf0fe463382227eca73/README.md#L73)):*
> ```Markdown
> -i coverage_level="150" \
> -i additional_sambamba_flags="" \
> -i additional_filter_commands="" \
> ```

can we give examples here?
___
*[README.md, line 84 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_sambamba_chanjo/36#-Mppo7dSCXEt6_QN9ZLX:-Mppo7dSCXEt6_QN9ZLY:b-6mlxcu) ([raw file](https://github.com/moka-guys/dnanexus_sambamba_chanjo/blob/b633a749fbb3c5553bc36cf0fe463382227eca73/README.md#L84)):*
> ```Markdown
> 
> ```bash
> python3.8 -m pytest --setup-show
> ```

this is run from within the app's folder?
___
*[README.md, line 87 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_sambamba_chanjo/36#-Mppo53r4-afa--31aaP:-Mppo53r4-afa--31aaQ:b-7smvhi) ([raw file](https://github.com/moka-guys/dnanexus_sambamba_chanjo/blob/b633a749fbb3c5553bc36cf0fe463382227eca73/README.md#L87)):*
> ```Markdown
> ```
> 
> * `test_inputs.py` - this tests that various combinations of input parameters don't brak the app.
> ```

break
___
*[src/test_inputs.py, line 11 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_sambamba_chanjo/36#-MpppezX9iTomJEygPOI:-MpppezY25LKvgW31q0L:b-k479zl) ([raw file](https://github.com/moka-guys/dnanexus_sambamba_chanjo/blob/b633a749fbb3c5553bc36cf0fe463382227eca73/src/test_inputs.py#L11)):*
> ```Python
> # TODO add to config file
> 
> app_version_to_test = "chanjo_sambamba_coverage_v1.11"
> ```

v1.13?
___
*[src/test_inputs.py, line 125 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_sambamba_chanjo/36#-MppprgHAoHKxObr5g9o:-MppprgHAoHKxObr5g9p:bwiy2b8) ([raw file](https://github.com/moka-guys/dnanexus_sambamba_chanjo/blob/b633a749fbb3c5553bc36cf0fe463382227eca73/src/test_inputs.py#L125)):*
> ```Python
> def run_dx_jobs():
>     """Run sambamba app with various combination of inputs"""
>     # Change to project 003_Sambamba_Testing
> ```

can we add a date into this project name?
___
*[src/test_inputs.py, line 145 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_sambamba_chanjo/36#-Mppq4rUBy4uVGpB_eyA:-Mppq4rVAmXqGIKwkNS_:b-n2myt0) ([raw file](https://github.com/moka-guys/dnanexus_sambamba_chanjo/blob/b633a749fbb3c5553bc36cf0fe463382227eca73/src/test_inputs.py#L145)):*
> ```Python
>         --yes --name {test_name} \
>         -i sambamba_bed=project-ByfFPz00jy1fk6PjpZ95F27J:file-FgQ0G1Q0jy1j1221FzBqG089 \
>         -i bamfile=project-G0FykV00GfYYJkF2B35Q27Yb:file-G0X31380zQkqYz293jk7VgJV \
> ```

should these bams be put into 001 or into this test project?
___
*[src/test_inputs.py, line 170 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_sambamba_chanjo/36#-MppqEup2qSGDd2GvRHg:-MppqEup2qSGDd2GvRHh:bu12x5l) ([raw file](https://github.com/moka-guys/dnanexus_sambamba_chanjo/blob/b633a749fbb3c5553bc36cf0fe463382227eca73/src/test_inputs.py#L170)):*
> ```Python
>     )
>     """
>     time.sleep(240)
> ```

is this sufficient? what if the job doesn't launch straightaway?
___
*[src/test_inputs.py, line 174 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_sambamba_chanjo/36#-MppqsdLD68EkIKljMQb:-MppqsdLD68EkIKljMQc:b-mzpi8o) ([raw file](https://github.com/moka-guys/dnanexus_sambamba_chanjo/blob/b633a749fbb3c5553bc36cf0fe463382227eca73/src/test_inputs.py#L174)):*
> ```Python
> 
> 
> def test_dx_inputs(run_dx_jobs):
> ```

sorry if being daft, but how is this called? by pytest because it starts with test_?
___
*[src/test_inputs.py, line 180 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_sambamba_chanjo/36#-Mppr2Hk-PH9XvMYSGhG:-Mppr2Hk-PH9XvMYSGhH:b-3ty82t) ([raw file](https://github.com/moka-guys/dnanexus_sambamba_chanjo/blob/b633a749fbb3c5553bc36cf0fe463382227eca73/src/test_inputs.py#L180)):*
> ```Python
> 
>     # test_111_standardSettings
>     stream = subprocess.run(
> ```

I think this is why you have the sleep statement? Can you do a dx describe and check the state?  I think the benchmarking tool does something similar- see https://github.com/moka-guys/benchmarking_tool/blob/c5f7ebe91fc2c67afb952f8b7392a1cd4af7c918/happy_vcfeval/precision_medicine.py#L351
___
*[src/test_outputs.py, line 62 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_sambamba_chanjo/36#-MpqXch2EwLgUFjZRTv8:-MpqXch3D54jEHQcEYqZ:b-3pcpk2) ([raw file](https://github.com/moka-guys/dnanexus_sambamba_chanjo/blob/b633a749fbb3c5553bc36cf0fe463382227eca73/src/test_outputs.py#L62)):*
> ```Python
>     f = open("pan_number_lookup.py", "a")
>     f.write(
>         re.search(
> ```

not sure what this is going? just splitting the file to create a dictionary?
___
*[src/test_outputs.py, line 74 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_sambamba_chanjo/36#-MpqcRYM6e1VSG00Wf4J:-MpqcRYM6e1VSG00Wf4K:b-8wej1m) ([raw file](https://github.com/moka-guys/dnanexus_sambamba_chanjo/blob/b633a749fbb3c5553bc36cf0fe463382227eca73/src/test_outputs.py#L74)):*
> ```Python
> def lookup_pan_number(sample_name):
>     # Get Pan number from Sample name
>     sample_pan = re.search("Pan[0-9]+", r.text, flags=re.DOTALL).group(0)
> ```

where is r.text coming from? is this sample_name?

**Comment by Graeme-Smith** [comment]
___
*[README.md, line 66 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_sambamba_chanjo/36#-MpuaE4a6PV87LmT3RN8:-MpuaE4bBRe9FRmFa2KC:bbwxwmm) ([raw file](https://github.com/moka-guys/dnanexus_sambamba_chanjo/blob/b633a749fbb3c5553bc36cf0fe463382227eca73/README.md#L66)):*
> ```
> -i bamfile=project-PXH0qBZHXlfT2JYf7aMcHMxQk:file-Bk5bbrm6YuQGjAIupujWk0FjO \
> -i bam_index=project-PXH0qBZHXlfT2JYf7aMcHMxQk:file-BppUJ6p6cJGPS2WWEIWqzMBOc \
> ```
These are not real files - can be confirmed using `dx describe`

**Comment by Graeme-Smith** [comment]
___
*[src/test_inputs.py, line 125 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_sambamba_chanjo/36#-MppprgHAoHKxObr5g9o:-Mpum7v-2NQ_8cO_HqLN:b3cywyf) ([raw file](https://github.com/moka-guys/dnanexus_sambamba_chanjo/blob/b633a749fbb3c5553bc36cf0fe463382227eca73/src/test_inputs.py#L125)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

can we add a date into this project name?
</blockquote></details>

Done. 003_211202_Sambamba_Testing

**Review by Graeme-Smith — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_sambamba_chanjo/36)* status: 0 of 5 files reviewed, 18 unresolved discussions (waiting on @aledj2)

___
*[README.md, line 1 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_sambamba_chanjo/36#-MppnBJx0FGVTw8X4Bfa:-Mpr2mr-CmqnBxe0dvVd:b-896fix) ([raw file](https://github.com/moka-guys/dnanexus_sambamba_chanjo/blob/b633a749fbb3c5553bc36cf0fe463382227eca73/README.md#L1)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

is this the right version/release?v1.13 now?
</blockquote></details>

Done.
___
*[README.md, line 43 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_sambamba_chanjo/36#-MppnZck-rSh0qu_hvV8:-Mpv4Gf39yVComu7lpR0:b-qer8r) ([raw file](https://github.com/moka-guys/dnanexus_sambamba_chanjo/blob/b633a749fbb3c5553bc36cf0fe463382227eca73/README.md#L43)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

some missing text here? from current master branch:

so the text must start ` and ...`, where ... is the additional filter command (also note the leading space before `and`).
</blockquote></details>

I removed this text because it is no longer required, I changed the code processing this input to make it more robust and forgiving of user input.
___
*[README.md, line 63 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_sambamba_chanjo/36#-MppnkB_AQBetxkFhYUK:-Mpr2uoP-JJnSJAfAbxw:b-896fix) ([raw file](https://github.com/moka-guys/dnanexus_sambamba_chanjo/blob/b633a749fbb3c5553bc36cf0fe463382227eca73/README.md#L63)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

> ```
> 11
> ```
v1.13
</blockquote></details>

Done.
___
*[README.md, line 64 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_sambamba_chanjo/36#-Mppnmzb4z0MxhnVpjyb:-MpxUy76EFX9jjpdFY34:b-896fix) ([raw file](https://github.com/moka-guys/dnanexus_sambamba_chanjo/blob/b633a749fbb3c5553bc36cf0fe463382227eca73/README.md#L64)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

example name
</blockquote></details>

Done.
___
*[README.md, line 65 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_sambamba_chanjo/36#-MppnprP2c247ME3Po4G:-MpxV42q0ZtYEfGIw4El:bbyrpha) ([raw file](https://github.com/moka-guys/dnanexus_sambamba_chanjo/blob/b633a749fbb3c5553bc36cf0fe463382227eca73/README.md#L65)):*
> ```
> project-PXH0qBZHXlfT2JYf7aMcHMxQk:file-cgEB1sJsCtyIzNnD6r
> ```
This is not a real file - can be confirmed using dx describe
___
*[README.md, line 72 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_sambamba_chanjo/36#-Mppo0rVAhnNCZAcJxSf:-MpvXOWM2I6x6Rpui6wT:b-896fix) ([raw file](https://github.com/moka-guys/dnanexus_sambamba_chanjo/blob/b633a749fbb3c5553bc36cf0fe463382227eca73/README.md#L72)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

can we give examples here?
</blockquote></details>

Done.
___
*[README.md, line 73 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_sambamba_chanjo/36#-MppnxPq6q5qg2xHdX7T:-MpvXPfI47QM8JTv2rP0:b-896fix) ([raw file](https://github.com/moka-guys/dnanexus_sambamba_chanjo/blob/b633a749fbb3c5553bc36cf0fe463382227eca73/README.md#L73)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

can we give examples here?
</blockquote></details>

Done.
___
*[README.md, line 84 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_sambamba_chanjo/36#-Mppo7dSCXEt6_QN9ZLX:-MpxVCA22_1KiHAdxBcg:b-ebsdz6) ([raw file](https://github.com/moka-guys/dnanexus_sambamba_chanjo/blob/b633a749fbb3c5553bc36cf0fe463382227eca73/README.md#L84)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

this is run from within the app's folder?
</blockquote></details>

Clarified running the pytest modules in the README
___
*[README.md, line 87 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_sambamba_chanjo/36#-Mppo53r4-afa--31aaP:-Mpug2uU6Vx-tqYa4AfZ:b-896fix) ([raw file](https://github.com/moka-guys/dnanexus_sambamba_chanjo/blob/b633a749fbb3c5553bc36cf0fe463382227eca73/README.md#L87)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

break
</blockquote></details>

Done.
___
*[src/test_inputs.py, line 11 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_sambamba_chanjo/36#-MpppezX9iTomJEygPOI:-Mpr34cK9j970BLTpEis:b-896fix) ([raw file](https://github.com/moka-guys/dnanexus_sambamba_chanjo/blob/b633a749fbb3c5553bc36cf0fe463382227eca73/src/test_inputs.py#L11)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

v1.13?
</blockquote></details>

Done.
___
*[src/test_inputs.py, line 145 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_sambamba_chanjo/36#-Mppq4rUBy4uVGpB_eyA:-Mpzuabt3VQvs1czYt5i:b-z746y7) ([raw file](https://github.com/moka-guys/dnanexus_sambamba_chanjo/blob/b633a749fbb3c5553bc36cf0fe463382227eca73/src/test_inputs.py#L145)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

should these bams be put into 001 or into this test project?
</blockquote></details>

I've added to the test project
___
*[src/test_inputs.py, line 170 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_sambamba_chanjo/36#-MppqEup2qSGDd2GvRHg:-MpxWvmME8PdYIfJ_36h:bwkvd7) ([raw file](https://github.com/moka-guys/dnanexus_sambamba_chanjo/blob/b633a749fbb3c5553bc36cf0fe463382227eca73/src/test_inputs.py#L170)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

is this sufficient? what if the job doesn't launch straightaway?
</blockquote></details>

I've replaced this with the function check_job_status()
___
*[src/test_inputs.py, line 174 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_sambamba_chanjo/36#-MppqsdLD68EkIKljMQb:-MpxXuk8CMNQaLeys_qk:bj6ofwe) ([raw file](https://github.com/moka-guys/dnanexus_sambamba_chanjo/blob/b633a749fbb3c5553bc36cf0fe463382227eca73/src/test_inputs.py#L174)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

sorry if being daft, but how is this called? by pytest because it starts with test_?
</blockquote></details>

That's exactly right.  Pytest will run any function matching this naming convention.
___
*[src/test_inputs.py, line 180 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_sambamba_chanjo/36#-Mppr2Hk-PH9XvMYSGhG:-MpxUfm29-g7BRHLrLjk:b-9j1ipr) ([raw file](https://github.com/moka-guys/dnanexus_sambamba_chanjo/blob/b633a749fbb3c5553bc36cf0fe463382227eca73/src/test_inputs.py#L180)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

I think this is why you have the sleep statement? Can you do a dx describe and check the state?  I think the benchmarking tool does something similar- see https://github.com/moka-guys/benchmarking_tool/blob/c5f7ebe91fc2c67afb952f8b7392a1cd4af7c918/happy_vcfeval/precision_medicine.py#L351
</blockquote></details>

Done. Added check_job_status() function and while loop
___
*[src/test_outputs.py, line 62 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_sambamba_chanjo/36#-MpqXch2EwLgUFjZRTv8:-MpzlUtU2eiEsv6tuII5:bdlujyk) ([raw file](https://github.com/moka-guys/dnanexus_sambamba_chanjo/blob/b633a749fbb3c5553bc36cf0fe463382227eca73/src/test_outputs.py#L62)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

not sure what this is going? just splitting the file to create a dictionary?
</blockquote></details>

Its basically taking the relevant section of  automate_demultiplex_config.py, which contains all the Pan number data, and saves it as the python module pan_number_lookup.py.  I tried to save & use automate_demultiplex_config.py directly but it threw errors due to dependencies which I didn't want to have to deal with.
___
*[src/test_outputs.py, line 74 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_sambamba_chanjo/36#-MpqcRYM6e1VSG00Wf4J:-MpznplR4sKEgngvFT2V:btnbx9w) ([raw file](https://github.com/moka-guys/dnanexus_sambamba_chanjo/blob/b633a749fbb3c5553bc36cf0fe463382227eca73/src/test_outputs.py#L74)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

where is r.text coming from? is this sample_name?
</blockquote></details>

r = requests.get(url, allow_redirects=True)

Bascically it returns the text from "https://raw.githubusercontent.com/moka-guys/automate_demultiplex/master/automate_demultiplex_config.py" which is parsed for the useful bits.  The original function just downloaded automate_demultiplex_config.py to use locally, however this caused problem due to broken dependencies in the script.

**Review by aledj2 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r2, 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_sambamba_chanjo/36)* status: 2 of 5 files reviewed, 2 unresolved discussions (waiting on @aledj2 and @Graeme-Smith)

___
*[README.md, line 43 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_sambamba_chanjo/36#-MppnZck-rSh0qu_hvV8:-Mq-11B1A9n1Kj7ZIXHD:b-5ctm3f) ([raw file](https://github.com/moka-guys/dnanexus_sambamba_chanjo/blob/b633a749fbb3c5553bc36cf0fe463382227eca73/README.md#L43)):*
<details><summary><i>Previously, Graeme-Smith (Graeme) wrote…</i></summary><blockquote>

I removed this text because it is no longer required, I changed the code processing this input to make it more robust and forgiving of user input.
</blockquote></details>

the sentence still doesn't make sense `Commands are appended to the existing filter created by using the .`
___
*[src/test_inputs.py, line 174 at r5](https://reviewable.io/reviews/moka-guys/dnanexus_sambamba_chanjo/36#-Mq-1jB52819Lg0VGh-n:-Mq-1jB52819Lg0VGh-o:b-u9ysiu) ([raw file](https://github.com/moka-guys/dnanexus_sambamba_chanjo/blob/c636e951affcda9dd125c12b49d4ee1612fe7c96/src/test_inputs.py#L174)):*
> ```Python
>     Wait for all jobs to finish before running tests
>     """
>     max_minutes_for_completion=15
> ```

FYI chanjo on WES with Pan493 takes 6 hours

**Review by aledj2 — COMMENTED** [review]
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_sambamba_chanjo/36)* status: 3 of 5 files reviewed, 2 unresolved discussions (waiting on @aledj2 and @Graeme-Smith)

**Comment by Graeme-Smith** [comment]
___
*[src/test_inputs.py, line 174 at r5](https://reviewable.io/reviews/moka-guys/dnanexus_sambamba_chanjo/36#-Mq-1jB52819Lg0VGh-n:-MqFQwHU99MzZg8Q1avU:b52ofo3) ([raw file](https://github.com/moka-guys/dnanexus_sambamba_chanjo/blob/c636e951affcda9dd125c12b49d4ee1612fe7c96/src/test_inputs.py#L174)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

FYI chanjo on WES with Pan493 takes 6 hours
</blockquote></details>

I chose files where Chanjo was relatively fast for this test suite - the ones specified take about 2 mins - these tests are essentially a check on the logic handling of the input arguments rather than the output.

**Review by Graeme-Smith — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_sambamba_chanjo/36)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @aledj2)

___
*[README.md, line 43 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_sambamba_chanjo/36#-MppnZck-rSh0qu_hvV8:-MqFUTJ1DyVLiS-GjoTo:b-896fix) ([raw file](https://github.com/moka-guys/dnanexus_sambamba_chanjo/blob/b633a749fbb3c5553bc36cf0fe463382227eca73/README.md#L43)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

the sentence still doesn't make sense `Commands are appended to the existing filter created by using the .`
</blockquote></details>

Done.

**Review by aledj2 — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_sambamba_chanjo/36#-:-MqFXDXdBNq-2t0nBhOc:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Graeme-Smith)

**Review by aledj2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_sambamba_chanjo/36)* status: 2 of 5 files reviewed, 2 unresolved discussions (waiting on @aledj2 and @Graeme-Smith)

___
*[README.md, line 5 at r7](https://reviewable.io/reviews/moka-guys/dnanexus_sambamba_chanjo/36#-MqQ13mt5_Uiesr0H7Io:-MqQ13mt5_Uiesr0H7Ip:bgkai7z) ([raw file](https://github.com/moka-guys/dnanexus_sambamba_chanjo/blob/58abf3580dc34eb76173e51dee79814566a811fb/README.md#L5)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
> <<<<<<< HEAD
> # dnanexus_sambamba_chanjo - v1.13
> =======
> # dnanexus_sambamba_chanjo - v1.12
> >>>>>>> a57c79dfddfb157b5f78c08162f72a64740d61bb
> ```
</details>

merge conflicts not addressed
___
*[README.md, line 39 at r7](https://reviewable.io/reviews/moka-guys/dnanexus_sambamba_chanjo/36#-MqQ18nZ0JtLLonodPWU:-MqQ18nZ0JtLLonodPWV:b-fzg0pn) ([raw file](https://github.com/moka-guys/dnanexus_sambamba_chanjo/blob/58abf3580dc34eb76173e51dee79814566a811fb/README.md#L39)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
> <<<<<<< HEAD
> This output is then parsed by a custom python script to generate a file that can be downloaded, and loaded into MOKA to generate clinical coverage reports.
> =======
> ### Read_chanjo.py
> A python script parses the sambamba and chanjo outputs and generates three files in formats that can be used downstream (see below)
> >>>>>>> a57c79dfddfb157b5f78c08162f72a64740d61bb
> ```
</details>

merge conflicts not addressed

**Review by Graeme-Smith — COMMENTED** [review]
> Reviewed 2 of 3 files at r7.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_sambamba_chanjo/36)* status: 3 of 5 files reviewed, 2 unresolved discussions (waiting on @aledj2 and @Graeme-Smith)

___
*[README.md, line 5 at r7](https://reviewable.io/reviews/moka-guys/dnanexus_sambamba_chanjo/36#-MqQ13mt5_Uiesr0H7Io:-MqU22O47dM2Qk0gKlok:b-896fix) ([raw file](https://github.com/moka-guys/dnanexus_sambamba_chanjo/blob/58abf3580dc34eb76173e51dee79814566a811fb/README.md#L5)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

> ```
> <<<<<<< HEAD
> # dnanexus_sambamba_chanjo - v1.13
> =======
> # dnanexus_sambamba_chanjo - v1.12
> >>>>>>> a57c79dfddfb157b5f78c08162f72a64740d61bb
> ```
merge conflicts not addressed
</blockquote></details>

Done.
___
*[README.md, line 39 at r7](https://reviewable.io/reviews/moka-guys/dnanexus_sambamba_chanjo/36#-MqQ18nZ0JtLLonodPWU:-MqU0euzBOURgdK602B3:b-896fix) ([raw file](https://github.com/moka-guys/dnanexus_sambamba_chanjo/blob/58abf3580dc34eb76173e51dee79814566a811fb/README.md#L39)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

> ```
> <<<<<<< HEAD
> This output is then parsed by a custom python script to generate a file that can be downloaded, and loaded into MOKA to generate clinical coverage reports.
> =======
> ### Read_chanjo.py
> A python script parses the sambamba and chanjo outputs and generates three files in formats that can be used downstream (see below)
> >>>>>>> a57c79dfddfb157b5f78c08162f72a64740d61bb
> ```
merge conflicts not addressed
</blockquote></details>

Done.

**Review by aledj2 — APPROVED** [review]
> Reviewed 2 of 3 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_sambamba_chanjo/36)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Graeme-Smith)

**Pull request merged**
